"""
Tests for the Commercial Invoice PDF generator's Bank Details box.

Constraint #9: PDF generation happens in memory — these tests read the
generated bytes straight back with pypdf, never touching disk.
"""
import pytest
from io import BytesIO

from pypdf import PdfReader

from apps.master_data.tests.factories import BankFactory
from pdf.commercial_invoice_generator import generate_commercial_invoice_pdf_bytes

from .factories import CommercialInvoiceFactory, CommercialInvoiceLineItemFactory


def _pdf_text(ci) -> str:
    reader = PdfReader(BytesIO(generate_commercial_invoice_pdf_bytes(ci)))
    return "\n".join(page.extract_text() for page in reader.pages)


@pytest.mark.django_db
class TestCommercialInvoicePdfBankDetails:
    def test_ad_code_and_lut_number_appear_in_bank_box(self):
        bank = BankFactory(ad_code="14012345678901", lut_number="AD070124000123A", lut_valid_until="2027-03-31")
        ci = CommercialInvoiceFactory(bank=bank)
        CommercialInvoiceLineItemFactory(ci=ci)
        text = _pdf_text(ci)
        assert "14012345678901" in text
        assert "AD070124000123A" in text

    def test_blank_ad_code_and_lut_omitted(self):
        """Matches the existing SWIFT/IBAN pattern — blank optional fields print nothing."""
        bank = BankFactory(ad_code="", lut_number="")
        ci = CommercialInvoiceFactory(bank=bank)
        CommercialInvoiceLineItemFactory(ci=ci)
        text = _pdf_text(ci)
        assert "AD CODE" not in text.upper()
        assert "LUT" not in text.upper()
