# Generated by Django 6.0.3 on 2026-03-22 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0014_add_delivery_address_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=20, unique=True)),
                ('po_date', models.DateField()),
                ('customer_no', models.CharField(blank=True, default='', max_length=100)),
                ('transaction_type', models.CharField(choices=[('IGST', 'Inter State Transaction (IGST)'), ('CGST_SGST', 'Same State Transaction (CGST+SGST)'), ('ZERO_RATED', 'Procurement for Export (Zero-Rated)')], max_length=20)),
                ('time_of_delivery', models.CharField(blank=True, default='', max_length=200)),
                ('tc_content', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REWORK', 'Rework'), ('PERMANENTLY_REJECTED', 'Permanently Rejected')], db_index=True, default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.bank')),
                ('country_of_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_as_delivery', to='master_data.organisationaddress')),
                ('internal_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_as_contact', to=settings.AUTH_USER_MODEL)),
                ('payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.paymentterm')),
                ('tc_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.tctemplate')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_as_vendor', to='master_data.organisation')),
            ],
            options={
                'db_table': 'purchase_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('item_code', models.CharField(blank=True, default='', max_length=100)),
                ('hsn_code', models.CharField(blank=True, default='', max_length=20)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('packaging_description', models.TextField(blank=True, default='')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taxable_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('igst_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('igst_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True)),
                ('cgst_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cgst_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True)),
                ('sgst_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sgst_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True)),
                ('total_tax', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchase_order.purchaseorder')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.uom')),
            ],
            options={
                'db_table': 'purchase_order_line_item',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='purchase_or_status_86ae3f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['created_by'], name='purchase_or_created_6ecbf4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['vendor'], name='purchase_or_vendor__50920f_idx'),
        ),
    ]
