# Generated by Django 6.0.3 on 2026-03-22 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0014_add_delivery_address_type'),
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_as_buyer', to='master_data.organisation'),
        ),
    ]
