# Generated by Django 6.0.3 on 2026-03-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_add_buyer_to_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='line_item_remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
