# Generated by Django 6.0.3 on 2026-05-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_add_line_item_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='internal_contract_number',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
