# Generated by Django 6.0.3 on 2026-05-25 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0017_add_shipment_fields'),
        ('purchase_order', '0005_change_internal_contact_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='incoterms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='master_data.incoterm'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='partial_shipment',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='port_of_discharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_as_discharge', to='master_data.port'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='port_of_final_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_as_final_destination', to='master_data.port'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='port_of_loading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_as_loading', to='master_data.port'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='transport_instruction',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='type_of_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='master_data.typeofpackage'),
        ),
    ]
