# Generated by Django 6.0.3 on 2026-03-16 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso2', models.CharField(help_text='ISO 3166-1 Alpha-2 code, e.g. IN', max_length=2, unique=True)),
                ('iso3', models.CharField(help_text='ISO 3166-1 Alpha-3 code, e.g. IND', max_length=3, unique=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'db_table': 'master_data_country',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Incoterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short code, e.g. FOB', max_length=10, unique=True)),
                ('full_name', models.CharField(help_text='e.g. Free On Board', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'master_data_incoterm',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'master_data_paymentterm',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PreCarriageBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Pre-Carriage By',
                'verbose_name_plural': 'Pre-Carriage By',
                'db_table': 'master_data_precarriageby',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Metric Tonnes', max_length=50)),
                ('abbreviation', models.CharField(help_text='e.g. MT', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'UOM',
                'verbose_name_plural': 'UOMs',
                'db_table': 'master_data_uom',
                'ordering': ['abbreviation'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='master_data.country')),
            ],
            options={
                'db_table': 'master_data_location',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(help_text='UN/LOCODE, e.g. INBOM', max_length=10, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ports', to='master_data.country')),
            ],
            options={
                'db_table': 'master_data_port',
                'ordering': ['name'],
            },
        ),
    ]
