# Generated by Django 6.0.3 on 2026-03-16 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('iec_code', models.CharField(blank=True, help_text='DGFT Importer–Exporter Code; exactly 10 alphanumeric chars', max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master_data_organisation',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('REGISTERED', 'Registered'), ('FACTORY', 'Factory'), ('OFFICE', 'Office')], max_length=20)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pin', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_name', models.CharField(max_length=150)),
                ('phone_country_code', models.CharField(blank=True, help_text='E.164 dial code, e.g. +91', max_length=5)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organisation_addresses', to='master_data.country')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='master_data.organisation')),
            ],
            options={
                'db_table': 'master_data_organisation_address',
                'ordering': ['address_type'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationTaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(help_text='e.g. GSTIN, PAN, VAT', max_length=50)),
                ('tax_code', models.CharField(max_length=50)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_codes', to='master_data.organisation')),
            ],
            options={
                'db_table': 'master_data_organisation_tax_code',
            },
        ),
        migrations.CreateModel(
            name='OrganisationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('EXPORTER', 'Exporter'), ('CONSIGNEE', 'Consignee'), ('BUYER', 'Buyer'), ('NOTIFY_PARTY', 'Notify Party')], max_length=20)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='master_data.organisation')),
            ],
            options={
                'db_table': 'master_data_organisation_tag',
                'unique_together': {('organisation', 'tag')},
            },
        ),
    ]
