# Generated by Django 6.0.3 on 2026-03-16 16:31

import apps.master_data.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 4217 currency code, e.g. USD, AED, INR', max_length=3, unique=True)),
                ('name', models.CharField(help_text='e.g. US Dollar', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'db_table': 'master_data_currency',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text="Short internal label, e.g. 'USD Operating Account'", max_length=255)),
                ('beneficiary_name', models.CharField(help_text='Account holder name as it appears on wire instructions', max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_address', models.TextField(blank=True)),
                ('account_number', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('CURRENT', 'Current'), ('SAVINGS', 'Savings'), ('CHECKING', 'Checking')], max_length=10)),
                ('swift_code', models.CharField(blank=True, help_text='Optional. 8 or 11 uppercase alphanumeric characters (ISO 9362).', max_length=11, validators=[apps.master_data.models._validate_swift])),
                ('iban', models.CharField(blank=True, help_text='Optional. Up to 34 alphanumeric characters.', max_length=34, validators=[apps.master_data.models._validate_iban])),
                ('routing_number', models.CharField(blank=True, max_length=50)),
                ('bank_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banks', to='master_data.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banks', to='master_data.currency')),
            ],
            options={
                'db_table': 'master_data_bank',
                'ordering': ['bank_name', 'nickname'],
            },
        ),
    ]
