# Generated by Django 6.0.3 on 2026-03-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_currency_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('body', models.TextField(help_text='Rich HTML content produced by the rich text editor')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisations', models.ManyToManyField(help_text='Organisations this template is available to', related_name='tc_templates', to='master_data.organisation')),
            ],
            options={
                'verbose_name': 'T&C Template',
                'verbose_name_plural': 'T&C Templates',
                'db_table': 'master_data_tctemplate',
                'ordering': ['name'],
            },
        ),
    ]
