# Generated by Django 6.0.3 on 2026-03-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_bank_intermediary_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='ad_code',
            field=models.CharField(blank=True, help_text='Authorised Dealer Code issued by the bank for customs/DGFT use', max_length=255),
        ),
    ]
