# Generated by Django 6.0.3 on 2026-03-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_bank_ad_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationtag',
            name='tag',
            field=models.CharField(choices=[('EXPORTER', 'Exporter'), ('CONSIGNEE', 'Consignee'), ('BUYER', 'Buyer'), ('NOTIFY_PARTY', 'Notify Party'), ('VENDOR', 'Vendor')], max_length=20),
        ),
    ]
