# Generated by Django 6.0.3 on 2026-03-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_add_bank_is_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organisationaddress',
            constraint=models.UniqueConstraint(fields=('organisation', 'address_type'), name='unique_address_type_per_organisation'),
        ),
    ]
