# Generated by Django 6.0.3 on 2026-03-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_unique_address_type_per_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='iec_code',
        ),
        migrations.AddField(
            model_name='organisationaddress',
            name='iec_code',
            field=models.CharField(blank=True, default='', help_text='DGFT Importer–Exporter Code for this address, e.g. AABCD1234E', max_length=10),
        ),
        migrations.AddField(
            model_name='organisationaddress',
            name='tax_code',
            field=models.CharField(blank=True, default='', help_text='Tax registration number for this address', max_length=50),
        ),
        migrations.AddField(
            model_name='organisationaddress',
            name='tax_type',
            field=models.CharField(blank=True, default='', help_text='Tax registration type for this address, e.g. GSTIN, PAN, VAT', max_length=50),
        ),
        migrations.DeleteModel(
            name='OrganisationTaxCode',
        ),
    ]
