# Generated by Django 6.0.3 on 2026-03-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_address_iec_tax_drop_taxcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationaddress',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='organisationaddress',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
