# Generated by Django 6.0.3 on 2026-04-08 08:37

from django.db import migrations


def populate_type_of_package(apps, schema_editor):
    """
    Populate TypeOfPackage with common packaging types used in international trade.
    Based on UN/CEFACT Recommendation 21 (standard packaging codes).
    """
    TypeOfPackage = apps.get_model("master_data", "TypeOfPackage")

    package_types = [
        # Containers & Bulk
        "Bags",
        "Bales",
        "Barrels",
        "Baskets",
        "Boxes",
        "Bundles",
        "Cartons",
        "Cases",
        "Casks",
        "Coils",
        "Containers",
        "Crates",
        "Drums",

        # Specialized packaging
        "Envelopes",
        "Flasks",
        "Jerricans",
        "Kegs",
        "Packages",
        "Packets",
        "Pallets",
        "Parcels",
        "Pieces",
        "Reels",
        "Rolls",
        "Sacks",
        "Sheets",
        "Skids",
        "Tanks",
        "Tubes",

        # Bulk/Loose
        "Bulk",
        "Loose",
        "Unpacked",

        # Transport units
        "Trays",
        "Totes",
        "Vials",
        "Wooden Cases",
    ]

    # Create all package types
    for name in package_types:
        TypeOfPackage.objects.get_or_create(name=name, defaults={"is_active": True})


def reverse_populate(apps, schema_editor):
    """Remove all seeded package types."""
    TypeOfPackage = apps.get_model("master_data", "TypeOfPackage")
    TypeOfPackage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0015_typeofpackage'),
    ]

    operations = [
        migrations.RunPython(populate_type_of_package, reverse_populate),
    ]
