# Generated by Django 6.0.3 on 2026-05-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0016_populate_type_of_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofpackage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
