# Generated by Django 6.0.3 on 2026-07-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0023_product_test_template_spec_to_charfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="lut_number",
            field=models.CharField(
                blank=True,
                help_text="Letter of Undertaking number filed with GST authorities",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="bank",
            name="lut_valid_until",
            field=models.DateField(
                blank=True, help_text="Date the current LUT number expires", null=True
            ),
        ),
    ]
