"""
Tests for the Purchase Order PDF generator's Bank Details box.

Constraint #9: PDF generation happens in memory — these tests read the
generated bytes straight back with pypdf, never touching disk.
"""
import pytest
from io import BytesIO

from pypdf import PdfReader

from apps.master_data.tests.factories import BankFactory
from pdf.purchase_order import generate_purchase_order_pdf_bytes

from .factories import PurchaseOrderFactory, PurchaseOrderLineItemFactory


def _pdf_text(po) -> str:
    reader = PdfReader(BytesIO(generate_purchase_order_pdf_bytes(po)))
    return "\n".join(page.extract_text() for page in reader.pages)


@pytest.mark.django_db
class TestPurchaseOrderPdfBankDetails:
    def test_ad_code_and_lut_number_appear_in_bank_box(self):
        bank = BankFactory(ad_code="14012345678901", lut_number="AD070124000123A", lut_valid_until="2027-03-31")
        po = PurchaseOrderFactory(bank=bank)
        PurchaseOrderLineItemFactory(purchase_order=po)
        text = _pdf_text(po)
        assert "14012345678901" in text
        assert "AD070124000123A" in text

    def test_blank_ad_code_and_lut_omitted(self):
        bank = BankFactory(ad_code="", lut_number="")
        po = PurchaseOrderFactory(bank=bank)
        PurchaseOrderLineItemFactory(purchase_order=po)
        text = _pdf_text(po)
        assert "AD CODE" not in text.upper()
        assert "LUT" not in text.upper()
