# Generated by Django 6.0.3 on 2026-03-19 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0007_bank_ad_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialInvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('hsn_code', models.CharField(blank=True, default='', max_length=8)),
                ('packages_kind', models.CharField(blank=True, default='', max_length=255)),
                ('total_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('rate_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
            ],
            options={
                'db_table': 'commercial_invoice_line_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CommercialInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_number', models.CharField(max_length=20, unique=True)),
                ('ci_date', models.DateField()),
                ('fob_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('freight', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('lc_details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REWORK', 'Rework'), ('PERMANENTLY_REJECTED', 'Permanently Rejected')], db_index=True, default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.bank')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_commercial_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commercial_invoice',
                'ordering': ['-created_at'],
            },
        ),
    ]
