# Generated by Django 6.0.3 on 2026-03-19 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial_invoice', '0001_initial'),
        ('master_data', '0007_bank_ad_code'),
        ('packing_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialinvoice',
            name='packing_list',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_invoice', to='packing_list.packinglist'),
        ),
        migrations.AddField(
            model_name='commercialinvoicelineitem',
            name='ci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='commercial_invoice.commercialinvoice'),
        ),
        migrations.AddField(
            model_name='commercialinvoicelineitem',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.uom'),
        ),
    ]
