# Generated by Django 6.0.3 on 2026-03-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_invoice', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialinvoice',
            name='signed_copy',
            field=models.FileField(blank=True, null=True, upload_to='signed_copies/ci/'),
        ),
    ]
