# Generated by Django 6.0.3 on 2026-04-17 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_invoice', '0002_rename_rate_amount_fields'),
        ('commercial_invoice', '0004_hsn_code_max_length_10'),
    ]

    operations = [
    ]
