# Generated by Django 5.1.15 on 2026-07-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificate_of_analysis", "0005_coaparameter_text_spec_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificateofanalysis",
            name="analyst_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="certificateofanalysis",
            name="qc_incharge_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
