# Generated by Django 5.1.15 on 2026-07-12 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentEditTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        help_text="e.g. 'proforma_invoice', 'packing_list' — matches AuditLog.document_type",
                        max_length=50,
                    ),
                ),
                (
                    "document_id",
                    models.PositiveIntegerField(
                        help_text="PK of the affected document"
                    ),
                ),
                ("document_number", models.CharField(max_length=30)),
                ("first_generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "edited_word_file",
                    models.FileField(
                        blank=True, null=True, upload_to="manual_edits/word/"
                    ),
                ),
                (
                    "edited_pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="manual_edits/pdf/"
                    ),
                ),
                ("edit_comment", models.TextField(blank=True, default="")),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manual_document_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "manual_edits_document_tracking",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document_type", "document_id"),
                        name="unique_document_tracking",
                    )
                ],
            },
        ),
    ]
