# Generated by Django 6.0.3 on 2026-03-19 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0007_bank_ad_code'),
        ('proforma_invoice', '0004_alter_proformainvoice_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_ref', models.CharField(max_length=100)),
                ('marks_numbers', models.TextField()),
                ('seal_number', models.CharField(max_length=100)),
                ('tare_weight', models.DecimalField(decimal_places=3, max_digits=12)),
                ('gross_weight', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'container',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContainerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_code', models.CharField(blank=True, default='', max_length=8)),
                ('item_code', models.CharField(max_length=100)),
                ('packages_kind', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('batch_details', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('net_weight', models.DecimalField(decimal_places=3, max_digits=12)),
                ('inner_packing_weight', models.DecimalField(decimal_places=3, max_digits=12)),
                ('item_gross_weight', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=12)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packing_list.container')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.uom')),
            ],
            options={
                'db_table': 'container_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_number', models.CharField(max_length=20, unique=True)),
                ('pl_date', models.DateField()),
                ('vessel_flight_no', models.CharField(blank=True, default='', max_length=100)),
                ('po_number', models.CharField(blank=True, default='', max_length=100)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('lc_number', models.CharField(blank=True, default='', max_length=100)),
                ('lc_date', models.DateField(blank=True, null=True)),
                ('bl_number', models.CharField(blank=True, default='', max_length=100)),
                ('bl_date', models.DateField(blank=True, null=True)),
                ('so_number', models.CharField(blank=True, default='', max_length=100)),
                ('so_date', models.DateField(blank=True, null=True)),
                ('other_references', models.CharField(blank=True, default='', max_length=255)),
                ('other_references_date', models.DateField(blank=True, null=True)),
                ('additional_description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REWORK', 'Rework'), ('PERMANENTLY_REJECTED', 'Permanently Rejected')], db_index=True, default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pl_as_buyer', to='master_data.organisation')),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pl_as_consignee', to='master_data.organisation')),
                ('country_of_final_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pl_as_final_destination', to='master_data.country')),
                ('country_of_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pl_as_origin', to='master_data.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_packing_lists', to=settings.AUTH_USER_MODEL)),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pl_as_exporter', to='master_data.organisation')),
                ('final_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pl_final_destination', to='master_data.location')),
                ('incoterms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.incoterm')),
                ('notify_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pl_as_notify_party', to='master_data.organisation')),
                ('payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.paymentterm')),
                ('place_of_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pl_place_of_receipt', to='master_data.location')),
                ('place_of_receipt_by_pre_carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pl_place_of_receipt_by_pre_carrier', to='master_data.location')),
                ('port_of_discharge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pl_port_of_discharge', to='master_data.port')),
                ('port_of_loading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pl_port_of_loading', to='master_data.port')),
                ('pre_carriage_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.precarriageby')),
                ('proforma_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_lists', to='proforma_invoice.proformainvoice')),
            ],
            options={
                'db_table': 'packing_list',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='container',
            name='packing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='packing_list.packinglist'),
        ),
    ]
