# Generated by Django 6.0.3 on 2026-03-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing_list', '0002_signed_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containeritem',
            name='hsn_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
