# Generated by Django 6.0.3 on 2026-03-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='signed_copy',
            field=models.FileField(blank=True, null=True, upload_to='signed_copies/pi/'),
        ),
    ]
