# Generated by Django 6.0.3 on 2026-03-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0003_pi_place_of_receipt_by_pre_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformainvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REWORK', 'Rework'), ('PERMANENTLY_REJECTED', 'Permanently Rejected')], db_index=True, default='DRAFT', max_length=30),
        ),
    ]
